ALTER TABLE public.profiles
DROP CONSTRAINT IF EXISTS profiles_position_check;

ALTER TABLE public.profiles
ADD CONSTRAINT profiles_position_check CHECK (
  position = ANY (ARRAY[
    'PROFESSOR',
    'ASSISTANT_PROFESSOR',
    'ASSOCIATE_PROFESSOR',
    'INSTRUCTOR',
    'DEAN',
    'CHAIR',
    'EXCHANGE_FACULTY',
    'Chief Accountant',
    'Accountant',
    'Accounting Staff',
    'Finance Officer',
    'Cashier',
    'Billing Staff',
    'Payroll Officer',
    'HR Manager',
    'HR Officer',
    'HR Staff',
    'Recruitment Officer',
    'Employee Relations Officer',
    'Training and Development Officer',
    'School Principal',
    'Assistant Principal',
    'Department Head',
    'Subject Coordinator',
    'Teacher',
    'Guidance Counselor',
    'School Nurse',
    'Associate Dean',
    'Program Chair',
    'Program Coordinator',
    'Faculty Member',
    'Laboratory Coordinator',
    'College Instructor',
    'Registrar',
    'Assistant Registrar',
    'Registration Officer',
    'Records Officer',
    'Enrollment Officer',
    'Transcript/Document Officer',
    'Chief Librarian',
    'Librarian',
    'Assistant Librarian',
    'Library Staff',
    'Circulation Assistant',
    'Library Technician',
    'Research Director',
    'Research Coordinator',
    'Research Adviser',
    'Research Staff',
    'Statistician',
    'Research Assistant',
    'Director of Student Affairs',
    'Student Affairs Officer',
    'Student Services Officer',
    'Student Activities Coordinator',
    'Scholarship Officer',
    'Publication Adviser',
    'Editor-in-Chief',
    'Managing Editor',
    'Associate Editor',
    'Staff Writer',
    'Layout Artist',
    'Graphic Designer',
    'Photojournalist',
    'MIS Director/Head',
    'MIS Officer',
    'System Administrator',
    'Network Administrator',
    'Database Administrator',
    'IT Support Specialist',
    'Computer Technician',
    'Web Developer',
    'Software Developer'
  ]::text[])
);