// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucjmbghkbfnknscqerfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjam1iZ2hrYmZua25zY3FlcmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODAyNTUsImV4cCI6MjA1OTc1NjI1NX0.TWnA5qWG5PhdT58Ythhb_Ep6LJlC63JYAfuxvNyg40U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});